# This workflow triggers the central CI/CD pipeline in DigitalLibraryCI
# without exposing full CI/CD logic in this repository

name: Trigger DigitalLibrary CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs
jobs:
  trigger-central-workflow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks executed as part of the job
    steps:
      # Trigger central CI/CD workflow in DigitalLibraryCI
      - name: Trigger central CI/CD workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          # Personal Access Token with repo and workflow permissions
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          # Central CI/CD repository
          repository: dolapo098/DigitalLibraryCI
          # Event type that the central workflow listens to
          event-type: run-digital-library-build
          # Inputs for the central workflow
          client-payload: |
            {
              "repo-name": "dolapo098/DigitalLibraryDatabase",
              "dacpac-path": "DigitalLibraryDatabase.sqlproj",
              "db-name": "DigitalLibraryTestDB",
              "sa-password": "${{ secrets.SA_PASSWORD }}"
            }
having doe that whats mextxx
