name: DigitalLibrary CI/CD

on:
  repository_dispatch:
    types: [run-digital-library-build]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.client_payload['repo-name'] }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # required for private repos

      - name: Build database project
        run: dotnet build ${{ github.event.client_payload['dacpac-path'] }} --configuration Release

      - name: Deploy database
        run: |
          echo "Deploying ${{ github.event.client_payload['db-name'] }}..."
          # Example: dotnet sql publish
        env:
          SA_PASSWORD: ${{ github.event.client_payload['sa-password'] }}
